name: AnarchyExploitFixes
version: ${project.version}
main: me.moomoo.anarchyexploitfixes.Main
description: ${project.description}
softdepend: [ ProtocolLib ]

commands:
  aef:
    usage: /<command>
    description: AnarchyExploitFixes commands
  toggleconnectionmsgs:
    usage: /<command>
    description: Toggle connection messages