name: AnarchyExploitFixes
version: ${project.version}
main: me.moomoo.anarchyexploitfixes.Main
description: ${project.description}
softdepend: [ ProtocolLib ]

commands:
  aef:
    usage: /<command>
    description: AnarchyExploitFixes commands
  toggleconnectionmsgs:
    usage: /<command>
    description: Toggle connection messages

permissions:
  anarchyexploitfixes.chatbypass:
    description: Bypass chat restrictions if enabled.
  anarchyexploitfixes.netherroofbypass:
    description: Bypass nether roof restrictions. (if enabled)
  anarchyexploitfixes.silentJoin:
    description: enable silent join mode
  anarchyexploitfixes.silentLeave:
    description: enable silent join mode